# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
    working_directory: ~/mercury
    docker:
        - image: circleci/node:11
        - image: rabbitmq:3-management
jobs:
    test:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      - v1-dependencies-
            - run: npm install
            - run: sleep 10
            - run:
                  name: Run jest and collect coverage reports
                  command: yarn test --coverage
            - store_artifacts:
                  path: coverage
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - persist_to_workspace:
                  root: ~/mercury
                  paths: .
    deploy:
        <<: *defaults
        steps:
            - attach_workspace:
                  at: ~/mercury
            - run:
                  name: build package files
                  command: npm run build
            - run:
                  name: Authenticate with registry
                  command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/mercury/.npmrc
            - run:
                  name: Publish package
                  command: npm publish

workflows:
    version: 2
    test-deploy:
        jobs:
            - test:
                  filters:
                      tags:
                          only: /^v.*/
                      branches:
                          only:
                              - master
                              - develop
            - deploy:
                  requires:
                      - test
                  filters:
                      branches:
                          only:
                              - master
